export default {
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_REQUEST_REJECTED: 'AUTH_REQUEST_REJECTED',
  AUTH_REQUEST_FULLFILED: 'AUTH_REQUEST_FULLFILED',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_REQUEST_REJECTED: 'SIGNUP_REQUEST_REJECTED',
  SIGNUP_REQUEST_FULLFILED: 'SIGNUP_REQUEST_FULLFILED',
  SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
  SIGNOUT_REQUEST_REJECTED: 'SIGNOUT_REQUEST_REJECTED',
  SIGNOUT_REQUEST_FULLFILED: 'SIGNOUT_REQUEST_FULLFILED',
};
