export default {
  POSTS_FETCH_ALL_REQUEST: 'POSTS_FETCH_ALL',
  POSTS_FETCH_ALL_SUCCESS: 'POSTS_FETCH_ALL_SUCCESS',
  POSTS_FETCH_ALL_FAILURE: 'POSTS_FETCH_ALL_FAILURE',
  POSTS_SEND_REQUEST: 'POSTS_SEND_REQUEST',
  POSTS_SEND_REQUEST_FAILURE: 'POSTS_SEND_REQUEST_FAILURE',
  POSTS_SEND_REQUEST_SUCCESS: 'POSTS_SEND_REQUEST_SUCCESS',
};
